### ISSUE TITLE
Feature Request: Option to recursively search --path

### ISSUE THREAD

**Issue by justinprince** [NUWCDIVNPT/stigman-watcher#137]
EvalSTIG --OutputPath creates two subfolders `basePath\$(hostname)\Checklists\ ` and then exports the .ckl files to the `Checklist` folder. I'm centralizing all of EvalSTIG .ckl outputs to a single place, but that single place ends up being <\basePath\$host1...20\Checklist\>, so before I can have SMW upload, I have to recurse through each subfolder and bring the checklist file up.

It's not a huge deal, but it would be handy if SMW could optionally recursively look through the subfolders inside of the directory assigned in the --path switch to account for this EvalSTIG output approach.

**Comment by cd-rite** [comment]
Hi @justinprince Watcher DOES recurse into sub-folders... Are you not getting that behavior?

**Comment by justinprince** [comment]
I don't believe I experienced that, but I could have been experiencing an overall import issue simultaneously. I ran the service in event mode and none of the .ckls were picked up, so I moved all the files up to the same folder and then ran a --one-shot and it worked, so my (maybe false) assumption was that it didn't like the subfolders. I will do some testing today and get back to you.

**Comment by cd-rite** [comment]
If you run in `event` mode, you'll need to use the `--add-existing` flag in order for it to import the files that are already there. Otherwise, it will only import files that arrive after the tool is started.
Alternatively, you could run in `scan` mode which maintains a history file of imported files as it relates to the current population of the monitored folder, and will import files that are there when it starts (if they are not in its history file).

**Comment by justinprince** [comment]
Confirmed that what you said was the case, thanks!
